services:
  frontend:
    build: ./fe
    image: node-gk-frontend:latest
    ports:  
      - "8080:80" 
    networks:
      - app-network
    deploy:
      replicas: 2 
    volumes:
      - ./fe/nginx.conf:/etc/nginx/nginx.conf 
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000 
      - NODE_ENV=development

  backend:
    build: ./be
    image: node-gk-backend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017/onlineshop
      - REDIS_URL=redis://redis:6379
    deploy:
      replicas: 3 

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    networks:
      - app-network
    ports:
      - "6379:6379"
networks:
  app-network:
    driver: overlay 
volumes:
  mongo-data:
    driver: local
